<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>generate_polychora</AssemblyName>
    <RootNamespace>D4BB.Geometry</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Tests\**\*.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MIConvexHull" Version="1.1.17.214" />
  </ItemGroup>

</Project>
